[project]
name = 'didactic_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.access_logs]
path = 'contracts/access_logs.clar'
clarity_version = 2
epoch = 2.5

[contracts.identity]
path = 'contracts/identity.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage_with_admin_role]
path = 'contracts/storage_with_admin_role.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
